import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const exampleRoot = resolve(import.meta.dir, "..");
const inputPath = join(exampleRoot, "generated", "system.catalog.json");
const outputPath = join(exampleRoot, "src", "generated", "system-catalog.ts");

const systemCatalog = JSON.parse(await readFile(inputPath, "utf8"));

const source = `// Generated by examples/web-runtime-prototype/scripts/generate-catalog-adapter.ts
// Do not edit by hand.

export const systemCatalog = ${JSON.stringify(systemCatalog, null, 2)} as const;

export type SystemCatalog = typeof systemCatalog;
export type CatalogSystem = typeof systemCatalog.catalogSystem;
export type CatalogComponent = (typeof systemCatalog.catalogComponents)[number];
export type CatalogArtifactReference = CatalogSystem["artifactReferences"][number];

export function getCatalogComponentById(id: string): CatalogComponent {
  const component = systemCatalog.catalogComponents.find((candidate) => candidate.id === id);
  if (!component) {
    throw new Error(\`unknown catalog component id: \${id}\`);
  }
  return component;
}
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source, "utf8");
console.log(`wrote ${outputPath}`);
