import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const exampleRoot = resolve(import.meta.dir, "..");
const inputPath = join(exampleRoot, "generated", "system.web.json");
const outputPath = join(exampleRoot, "src", "generated", "system-web.ts");

const webRuntime = JSON.parse(await readFile(inputPath, "utf8"));

const source = `// Generated by examples/web-runtime-prototype/scripts/generate-web-adapter.ts
// Do not edit by hand.

export const webRuntime = ${JSON.stringify(webRuntime, null, 2)} as const;

export type WebRuntime = typeof webRuntime;
export type WebComponent = (typeof webRuntime.webComponents)[number];
export type WebArtifact = WebComponent["artifacts"]["required"][number];
export type WebExample = WebComponent["examples"][number];

export function getWebComponentById(id: string): WebComponent {
  const component = webRuntime.webComponents.find((candidate) => candidate.id === id);
  if (!component) {
    throw new Error(\`unknown web component id: \${id}\`);
  }
  return component;
}

export function getWebComponentByTagName(tagName: string): WebComponent {
  const component = webRuntime.webComponents.find((candidate) => candidate.tagName === tagName);
  if (!component) {
    throw new Error(\`unknown web component tag: \${tagName}\`);
  }
  return component;
}
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source, "utf8");
console.log(`wrote ${outputPath}`);
